server:
  port: 9622
spring:
  application:
    name: remexs-corp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.110.13:3306/remexs_corp?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
mybatis-plus:
  mapper-locations: classpath*:**/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.remexs.**.entity,com.remexs.common.dto.impl
  #type-enums-package: com.remexs.push.model.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: cn.jeefast.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: com.remexs.data.mybatis.handler.AutoColumnFillHandler
    #自定义SQL注入器
    #sql-injector: cn.jeefast.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

eureka:
  instance:
    statusPageUrlPath: /swagger-ui.html
    healthCheckUrlPath: /health
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
             