spring:
  application:
    name: remexs-eureka
server:
  port: 8761
eureka:
  instance:
    statusPageUrlPath: /swagger-ui.html
    healthCheckUrlPath: /health
  client:
    #false:不作为一个客户端注册到注册中心
    registerWithEureka: false
    #为true时，可以启动，但报异常：Cannot execute request on any known server
    fetchRegistry: false